openapi: 3.0.0
info:
  description: >
    Backend to access navigator, landlord, and property information from dynamo
    DB
  version: "0.1.0"
  title: Housing Hub REST Api
  contact:
    email: jkropko@codeforcharlottesville.org
  license:
    name: GPL-3.0

tags:
  - name: navigator
    description: People who help others "navigate" the housing hub system
  - name: landlord
    description: People who own property and wish to lease it
  - name: property
    description: Real property, the actual apartment, condo, or house
  - name: authentication
    description: Logging in, logging out, and site security  

paths:
  /navigator:
    get:
      tags: 
        - navigator
      summary: Retrieves a navigator from the backend DB
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the navigator to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A navigator object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Navigator'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags: 
        - navigator      
      summary: Creates navigator if does not already exist.
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Navigator'

      responses:
        '200':
          description: Newly created navigator
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Navigator'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags: 
        - navigator    
      summary: Update existing navigator.
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Navigator'

      responses:
        '200':
          description: Newly updated navigator
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Navigator'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


    delete:
      tags: 
        - navigator    
      summary: Delete existing navigator.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the navigator to retrieve
          schema:
            type: string

      responses:
        '200':
          description: Newly deleted navigator
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Navigator'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /landlord:
    get:
      tags: 
        - landlord    
      summary: Retrieves a landlord from the backend DB
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the landlord to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A landlord object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landlord'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags: 
        - landlord    
      summary: Creates landlord if does not already exist.
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landlord'

      responses:
        '200':
          description: Newly created landlord
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landlord'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags: 
        - landlord    
      summary: Update existing landlord.
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landlord'

      responses:
        '200':
          description: Newly updated landlord
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Landlord'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


    delete:
      tags: 
        - landlord    
      summary: Delete existing landlord.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the landlord to retrieve
          schema:
            type: string

      responses:
        '200':
          description: Newly deleted landlord
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Navigator'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /property:
    get:
      tags: 
        - property    
      summary: Retrieves a property from the backend DB
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the property to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A property object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags: 
        - property    
      summary: Creates property if does not already exist.
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'

      responses:
        '200':
          description: Newly created property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags: 
        - property    
      summary: Update existing property.
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'

      responses:
        '200':
          description: Newly updated property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


    delete:
      tags: 
        - property    
      summary: Delete existing property.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the property to retrieve
          schema:
            type: string

      responses:
        '200':
          description: Newly deleted property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Navigator'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/register:
    post:
      tags: 
        - authentication    
      summary: creates a new user
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/createUserRequest'

      responses:
        '200':
          description: Newly created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createUserResponse'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      tags: 
        - authentication    
      summary: retrieves a jwt token from the server, acting as user authentication
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginRequest'

      responses:
        '200':
          description: The newly created jwt token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jwt'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'  

  /auth/status:
    get:
      tags: 
        - authentication    
      summary: Verify if a user's is currently valid and see jwt token payload
      responses:
        '200':
          description: jwt payload for user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jwtPayload'
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  schemas:

    createUserRequest:
      type: object
      properties:
        user:
           $ref: '#/components/schemas/User'
        navigator:
           $ref: '#/components/schemas/Navigator'
        landlord:
           $ref: '#/components/schemas/Landlord'                   
        
    createUserResponse:
      type: object
      properties:
        jwt:
           $ref: '#/components/schemas/jwt'
        user:
           $ref: '#/components/schemas/User'


    loginRequest:
      type: object
      properties:
        username:
          type: string
          description: username for the user logging in 
          example: david0124816
        password:
          type: string
          description: password for the user
          example: sercretpassword

    jwt:
      type: object
      properties:
        jwt: 
          type: string
          description: utf-8 encoded jwt token for the user encrypted with HS256
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1ODU0Mjk3NjUsInVpZCI6ImI0OTM1OGZjLTcxMzctMTFlYS1iZDRmLWU0NzBiOGI2MTY4MyIsIm5hbWUiOiJkYXZpZCBnb2xkc3RlaW4ifQ.q6p91KS8iOme-K5baVlVSFBPW8K0kjdSJZ-IWSOF-cw

    jwtPayload:
      type: object
      properties:
        exp:
          type: integer
          description: UTC timestamp when the token will expire
          example: 1585429765
        uuid:
          type: string
          description: UUID of the user in the database
          example: "u-b49358fc-7137-11ea-bd4f-e470b8b61683"
        user_name:
          type: string
          description: user name of the user
          example: david01235
        role:
          type: string
          description: what the user does in this system
          example: "navigator"

    User:
      type: object
      properties:
        id:
          type: string
          description: uuid of the user starting with "u-"
          example: "u-sdf23f-f23joif-sfdh23-sefue"
        user_name:
          type: string
          description: unique username of the user
          example: "david2134"
        role:
          type: string
          description: what the user does in the system
          example: "navigator"
        is_admin:
          type: boolean
          description: is the user an admin in system?
          example: true

    Error:
      type: object
      properties:
        code:
          type: integer
          description: The code of the error.
          example: 500
        error:
          type: string
          description: Explanation of the error.
          example: Internal server error
          
    Navigator:
      type: object
      properties:
        id:
          type: string
          description: The ID of the navigator

    Landlord:
      type: object
      properties:
        id:
          type: string
          description: The ID of the landlord

    Property:
      type: object
      properties:
        id:
          type: string
          description: The ID of the property