service: housinghub-client

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

custom:
  client:
    bucketName: housinghub-client-${self:provider.stage}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
