from python:3.6
run apt-get update
workdir /usr/housinghub
run python3 --version

# copy app and copy dependencies
copy . /usr/housinghub
run pip install -r requirements.txt

# generate documentation
run python api/swagger-yaml-to-html.py < api/swagger.yml > api/index.html

# configure app
env FLASK_APP src/server.py
run > config.cfg
run echo 'HOST = "0.0.0.0"' >> config.cfg
run echo 'DEBUG = True' >> config.cfg
run cat config.cfg
# configure saving
env DYNAMO_DB_ENDPOINT "tcp://test"
env PORT "5000"
# run app
CMD ./docker_start.sh