# This workflow runs backend tests, then executes the serverless deploy dev stage

name: Deploy Dev Backend

on:
  push:
    branches: [ main ]

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

  deploy:
    name: Deploy Dev Backend
    runs-on: ubuntu-latest
    needs: [backend]
    steps:
    - uses: actions/checkout@main
    - name: npm install
      uses: actions/npm@main
      with:
        args: install
    - name: serverless deploy
      uses: serverless/github-action@main
      with:
        args: deploy --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
